
# build env args
ARG VITE_API_KEY=""
ARG VITE_AUTH_DOMAIN=""
ARG VITE_PROJECT_ID=""
ARG VITE_STORAGE_BUCKET=""
ARG VITE_MESSAGING_SENDER_ID=""
ARG VITE_APP_ID=""
ARG VITE_MEASUREMENT_ID=""
ARG VITE_CLOUDINARY_PROJECT=""
ARG VITE_CLOUDINARY_PRESET=""

FROM node:lts-alpine3.16 as build

WORKDIR /app
COPY package*.json ./
COPY yarn.lock  ./
COPY . ./
RUN apk update && apk add --no-cache bash
RUN bash
COPY . /

ARG VITE_API_KEY
ARG VITE_AUTH_DOMAIN
ARG VITE_PROJECT_ID
ARG VITE_STORAGE_BUCKET
ARG VITE_MESSAGING_SENDER_ID
ARG VITE_APP_ID
ARG VITE_MEASUREMENT_ID
ARG VITE_CLOUDINARY_PROJECT
ARG VITE_CLOUDINARY_PRESET


ENV VITE_API_KEY=$VITE_API_KEY
ENV VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
ENV VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
ENV VITE_PROJECT_ID=$VITE_PROJECT_ID
ENV VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
ENV VITE_APP_ID=$VITE_APP_ID
ENV VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID
ENV VITE_CLOUDINARY_PROJECT=$VITE_CLOUDINARY_PROJECT
ENV VITE_CLOUDINARY_PRESET=$VITE_CLOUDINARY_PRESET

RUN yarn install
RUN yarn build

FROM node:lts-alpine3.16 as runtime

ARG VITE_API_KEY
ARG VITE_AUTH_DOMAIN
ARG VITE_PROJECT_ID
ARG VITE_STORAGE_BUCKET
ARG VITE_MESSAGING_SENDER_ID
ARG VITE_APP_ID
ARG VITE_MEASUREMENT_ID
ARG VITE_CLOUDINARY_PROJECT
ARG VITE_CLOUDINARY_PRESET

ENV VITE_API_KEY=$VITE_API_KEY
ENV VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
ENV VITE_PROJECT_ID=$VITE_PROJECT_ID
ENV VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
ENV VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
ENV VITE_APP_ID=$VITE_APP_ID
ENV VITE_MEASUREMENT_ID=$VITE_MEASUREMENT_ID
ENV VITE_CLOUDINARY_PROJECT=$VITE_CLOUDINARY_PROJECT
ENV VITE_CLOUDINARY_PRESET=$VITE_CLOUDINARY_PRESET

RUN yarn global add serve
USER node
WORKDIR /app
COPY --from=build /app/build .
EXPOSE 8080

CMD ["serve", "-p", "8080", "-s", "-n", "."]